# Generated by Django 5.2.1 on 2025-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
